# Generated by Django 2.2.7 on 2019-11-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
